import {readFile,writeFile,mkdir,rm,cp,readdir} from 'node:fs/promises';
import {layout,heading,picture,paragraphs,esc,imagePath} from '../src/render.mjs';
import {isPast,ticketSection,productionCards,productionDetail,heroSlides} from '../src/productions.mjs';
const site=JSON.parse(await readFile('content/site.json','utf8'));
const gallery=JSON.parse(await readFile('content/gallery.json','utf8'));
const galleryHTML=photos=>`<div class="gallery">${photos.filter(x=>imagePath(x.image)).map(x=>`<button data-photo="${esc(x.image)}" data-caption="${esc(x.caption||'')}" aria-label="Enlarge: ${esc(x.alt)}">${picture(x.image,x.alt)}<span class="enlarge" aria-hidden="true">+</span></button>`).join('')}</div>`;
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
async function save(route,body,title,current=route){const dir='dist'+route;await mkdir(dir,{recursive:true});await writeFile(dir+'index.html',layout(site,title,body,current));}
async function entries(folder){return (await Promise.all((await readdir('content/'+folder).catch(e=>{if(e.code==='ENOENT')return [];throw e;})).filter(f=>f.endsWith('.json')).map(async f=>{const slug=f.slice(0,-5);if(!/^[a-z0-9][a-z0-9-]*$/.test(slug))throw Error('Invalid content filename: '+f);return {...JSON.parse(await readFile('content/'+folder+'/'+f)),slug};}))).filter(x=>x.published===true);}
const news=(await entries('news')).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const team=await entries('team');const productions=await entries('productions');
const past=productions.filter(isPast).sort((a,b)=>b.year-a.year||b.slug.localeCompare(a.slug));
const current=productions.filter(p=>p.status==='current');
const upcoming=productions.filter(p=>p.status==='upcoming');
const date=d=>{const x=new Date(d);return isNaN(x)?'':new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeZone:'UTC'}).format(x);};
const newsCards=list=>list.length?`<div class="cards">${list.map(n=>`<article class="card"><a href="/news/${n.slug}/">${picture(n.image,n.imageAlt||n.title)}<h3>${esc(n.title)}</h3></a><time>${esc(date(n.date))}</time><p>${esc(n.summary)}</p></article>`).join('')}</div>`:'<p class="empty">Company news and announcements will appear here.</p>';
await save('/',`<section class="hero hero-dynamic">${heroSlides(site)}<div class="hero-copy"><p class="eyebrow">From rehearsal room to spotlight</p><h1>${esc(site.heroTitle)}</h1><p class="hero-tagline">${esc(site.intro)}</p><div class="hero-bottom"><a class="text-link" href="/whats-on/">See what’s on ↗</a></div></div></section>${ticketSection(current[0])}
<section class="showcase" aria-label="Discover Top Hat and Tails"><a class="showcase-card" href="/productions/#gallery">${picture('/uploads/stage-11.webp','Performers dancing with umbrellas on stage')}<div><span class="eyebrow">The performances</span><h2>On stage.</h2><span class="text-link">Explore the gallery ↗</span></div></a><a class="showcase-card" href="/productions/#gallery">${picture(site.featureImage,'Two performers embracing in a scene')}<div><span class="eyebrow">The stories</span><h2>In the moment.</h2><span class="text-link">Look a little closer ↗</span></div></a><a class="showcase-card" href="/team/">${picture('/uploads/rehearsal.jpg','Company members practising a kick line in rehearsal')}<div><span class="eyebrow">The people</span><h2>Behind the curtain.</h2><span class="text-link">Meet the company ↗</span></div></a></section>
<section class="company-section"><div class="company-photo">${picture(site.companyImage,'Top Hat and Tails company group photograph')}</div><div class="company-copy"><p class="eyebrow">We are Top Hat and Tails</p><h2>A company.<br>A shared passion.</h2>${paragraphs(site.about)}<a class="text-link" href="/team/">Discover the company <span aria-hidden="true">↗</span></a></div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">From the company</p><h2>News &amp; updates</h2></div><a class="text-link" href="/news/">All news ↗</a></div>${newsCards(news.slice(0,3))}</section>
<section class="join-panel"><p class="eyebrow">Your next act</p><h2>Be part of <em>THAT.</em></h2><p>${esc(site.joinIntro)}</p><a class="button" href="/join/">Join the company <span aria-hidden="true">↗</span></a></section>`,'Home');
await save('/news/',heading('Latest updates','Company news')+`<section class="section">${newsCards(news)}</section>`,'News');
for(const n of news)await save('/news/'+n.slug+'/',heading('Company news',n.title)+`<article class="reading"><a class="back" href="/news/">Back to news</a><p>${esc(date(n.date))}</p>${picture(n.image,n.imageAlt||n.title,'article-cover')}${paragraphs(n.body)}</article>`,n.title,'/news/');
await save('/team/',heading('The company','Our team')+`<section class="section"><div class="team-banner">${picture(site.companyImage,'The Top Hat and Tails company together')}</div>${paragraphs(site.about)}${team.length?`<div class="cards">${team.sort((a,b)=>(a.order||0)-(b.order||0)).map(t=>`<article class="card">${picture(t.image,t.name,'portrait')}<h2>${esc(t.name)}</h2><p class="role">${esc(t.role)}</p>${paragraphs(t.bio)}</article>`).join('')}</div>`:'<p class="empty">Meet-the-team profiles are coming soon.</p>'}</section>`,'Our team');
await save('/productions/',heading('Our archive','Past productions','The shows, the music and the memories.')+`<section class="section">${productionCards(past)}<div id="gallery" class="gallery-heading"><p class="eyebrow">The company in pictures</p><h2>Moments in the spotlight</h2></div>${galleryHTML(gallery.photos||[])}</section>`,'Past productions');
await save('/whats-on/',heading('Plan your next visit','Current & upcoming productions')+`<section class="section"><h2>Current production</h2>${current.length?productionCards(current):'<p>Our next production announcement is coming soon.</p>'}<h2>Coming up</h2>${upcoming.length?productionCards(upcoming):'<p>Future productions will be announced here.</p>'}</section>${ticketSection(current[0])}`,'What’s on');
for(const p of productions)await save('/productions/'+p.slug+'/',heading(String(p.year||''),p.title)+`<section class="section"><a class="back" href="${isPast(p)?'/productions/':'/whats-on/'}">Back to ${isPast(p)?'past productions':'what’s on'}</a>${productionDetail(p)}${galleryHTML(p.photos||[])}</section>${isPast(p)?'':ticketSection(p)}`,p.title,isPast(p)?'/productions/':'/whats-on/');
await save('/join/',heading('Join the company','Take your place',site.joinIntro)+`<section class="reading"><form class="form" id="application"><label for="name">Full name</label><input id="name" name="name" autocomplete="name" required maxlength="120"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="phone">Phone number <span class="hint">(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="40"><fieldset><legend>What interests you?</legend>${['Performing','Backstage','Costumes','Technical','Other'].map(x=>`<label class="check"><input name="interests" type="checkbox" value="${x}">${x}</label>`).join('')}</fieldset><label for="experience">Tell us a little about yourself <span class="hint">(optional)</span></label><textarea id="experience" name="experience" maxlength="3000"></textarea><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="check"><input type="checkbox" name="consent" required>I have read the <a href="/privacy/">privacy notice</a> and agree to my details being used to respond to this application.</label><div class="turnstile-slot" data-action="application"></div><button class="button" disabled>Send application</button><p class="status" role="status">Checking application availability…</p></form><noscript>JavaScript is required to submit this form securely.</noscript></section>`,'Join us');
await save('/privacy/',heading('Your information','Privacy notice')+`<section class="reading">${site.privacyNotice?paragraphs(site.privacyNotice):'<p>Applications are not open yet. The company’s application privacy notice will be published here before the form opens.</p>'}</section>`,'Privacy');
await writeFile('dist/404.html',layout(site,'Page not found',heading('404','That page isn’t here')+'<section class="reading"><a class="button" href="/">Back to the homepage</a></section>'));
// Only the Worker receives private data. No private JSON or source tree enters static assets.
let worker=await readFile('src/worker.mjs','utf8');worker=worker.replace("import {layout,heading,loginPage,membersPage,esc} from './render.mjs';",(await readFile('src/render.mjs','utf8')).replace(/export /g,''));
worker=worker.replace('/* CONTENT_INJECTION */',`const SITE=${JSON.stringify(site)};const MEMBERS=${await readFile('private/members.json','utf8')};`);await writeFile('dist/_worker.js',worker);
await writeFile('dist/_routes.json',JSON.stringify({version:1,include:['/api/*','/members','/members/*','/admin','/admin/*','/_worker.js*','/private/*','/content/*'],exclude:[]}));
await writeFile('dist/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n');
console.log(`Built ${7+news.length+productions.length} public pages; protected member route; Decap editor; ${news.length} news, ${team.length} team and ${productions.length} production entries.`);
