import {readFile,writeFile,mkdir,rm,cp,readdir} from 'node:fs/promises';
import {layout,heading,picture,paragraphs,esc,imagePath} from '../src/render.mjs';
const site=JSON.parse(await readFile('content/site.json','utf8'));
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
async function save(route,body,title,current=route){const dir='dist'+route;await mkdir(dir,{recursive:true});await writeFile(dir+'index.html',layout(site,title,body,current));}
async function entries(folder){return (await Promise.all((await readdir('content/'+folder).catch(e=>{if(e.code==='ENOENT')return [];throw e;})).filter(f=>f.endsWith('.json')).map(async f=>{const slug=f.slice(0,-5);if(!/^[a-z0-9][a-z0-9-]*$/.test(slug))throw Error('Invalid content filename: '+f);return {...JSON.parse(await readFile('content/'+folder+'/'+f)),slug};}))).filter(x=>x.published===true);}
const news=(await entries('news')).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const team=await entries('team');const productions=await entries('productions');
const date=d=>{const x=new Date(d);return isNaN(x)?'':new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeZone:'UTC'}).format(x);};
const newsCards=list=>list.length?`<div class="cards">${list.map(n=>`<article class="card"><a href="/news/${n.slug}/">${picture(n.image,n.imageAlt||n.title)}<h3>${esc(n.title)}</h3></a><time>${esc(date(n.date))}</time><p>${esc(n.summary)}</p></article>`).join('')}</div>`:'<p class="empty">Company news and announcements will appear here.</p>';
await save('/',`<section class="hero"><div class="hero-copy"><p class="eyebrow">${esc(site.description)}</p><h1>${esc(site.heroTitle)}</h1><p>${esc(site.intro)}</p><div class="buttons"><a class="button" href="/join/">Join the company</a><a class="button outline" href="/productions/">Explore our productions</a></div></div>${picture(site.heroImage,site.heroAlt,'hero-image').replace('loading="lazy"','fetchpriority="high"')}</section><section class="section"><div class="section-head"><div><p class="eyebrow">Company news</p><h2>From the rehearsal room</h2></div><a href="/news/">All news</a></div>${newsCards(news.slice(0,3))}<div class="join-panel"><h2>Find your place with Top Hat and Tails</h2><p>${esc(site.joinIntro)}</p><a class="button" href="/join/">Apply to join</a></div></section>`,'Home');
await save('/news/',heading('Latest updates','Company news')+`<section class="section">${newsCards(news)}</section>`,'News');
for(const n of news)await save('/news/'+n.slug+'/',heading('Company news',n.title)+`<article class="reading"><a class="back" href="/news/">Back to news</a><p>${esc(date(n.date))}</p>${picture(n.image,n.imageAlt||n.title,'article-cover')}${paragraphs(n.body)}</article>`,n.title,'/news/');
await save('/team/',heading('The company','Our team')+`<section class="section">${paragraphs(site.about)}${team.length?`<div class="cards">${team.sort((a,b)=>(a.order||0)-(b.order||0)).map(t=>`<article class="card">${picture(t.image,t.name,'portrait')}<h2>${esc(t.name)}</h2><p class="role">${esc(t.role)}</p>${paragraphs(t.bio)}</article>`).join('')}</div>`:'<p class="empty">Meet-the-team profiles are coming soon.</p>'}</section>`,'Our team');
await save('/productions/',heading('On stage','Previous productions','A look back at Top Hat and Tails on stage.')+`<section class="section">${productions.length?`<div class="cards">${productions.sort((a,b)=>(b.year||0)-(a.year||0)).map(p=>`<article class="card"><a href="/productions/${p.slug}/">${picture(p.cover,p.title)}<h2>${esc(p.title)}</h2></a><p>${esc(p.year)}</p></article>`).join('')}</div>`:'<p class="empty">Production galleries are coming soon.</p>'}</section>`,'Previous productions');
for(const p of productions)await save('/productions/'+p.slug+'/',heading(String(p.year||''),p.title)+`<section class="section"><a class="back" href="/productions/">Back to productions</a>${paragraphs(p.description)}<div class="gallery">${(p.photos||[]).filter(x=>imagePath(x.image)).map(x=>`<button data-photo="${esc(x.image)}" data-caption="${esc(x.caption||'')}" aria-label="Enlarge: ${esc(x.alt||x.caption||p.title)}">${picture(x.image,x.alt||x.caption||p.title)}</button>`).join('')}</div></section>`,p.title,'/productions/');
await save('/join/',heading('Join the company','Take your place',site.joinIntro)+`<section class="reading"><form class="form" id="application"><label for="name">Full name</label><input id="name" name="name" autocomplete="name" required maxlength="120"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="phone">Phone number <span class="hint">(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="40"><fieldset><legend>What interests you?</legend>${['Performing','Backstage','Costumes','Technical','Other'].map(x=>`<label class="check"><input name="interests" type="checkbox" value="${x}">${x}</label>`).join('')}</fieldset><label for="experience">Tell us a little about yourself <span class="hint">(optional)</span></label><textarea id="experience" name="experience" maxlength="3000"></textarea><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="check"><input type="checkbox" name="consent" required>I have read the <a href="/privacy/">privacy notice</a> and agree to my details being used to respond to this application.</label><div class="turnstile-slot" data-action="application"></div><button class="button" disabled>Send application</button><p class="status" role="status">Checking application availability…</p></form><noscript>JavaScript is required to submit this form securely.</noscript></section>`,'Join us');
await save('/privacy/',heading('Your information','Privacy notice')+`<section class="reading">${site.privacyNotice?paragraphs(site.privacyNotice):'<p>Applications are not open yet. The company’s application privacy notice will be published here before the form opens.</p>'}</section>`,'Privacy');
await writeFile('dist/404.html',layout(site,'Page not found',heading('404','That page isn’t here')+'<section class="reading"><a class="button" href="/">Back to the homepage</a></section>'));
// Only the Worker receives private data. No private JSON or source tree enters static assets.
let worker=await readFile('src/worker.mjs','utf8');worker=worker.replace("import {layout,heading,loginPage,membersPage,esc} from './render.mjs';",(await readFile('src/render.mjs','utf8')).replace(/export /g,''));
worker=worker.replace('/* CONTENT_INJECTION */',`const SITE=${JSON.stringify(site)};const MEMBERS=${await readFile('private/members.json','utf8')};`);await writeFile('dist/_worker.js',worker);
await writeFile('dist/_routes.json',JSON.stringify({version:1,include:['/api/*','/members','/members/*','/admin','/admin/*','/_worker.js*','/private/*','/content/*'],exclude:[]}));
await writeFile('dist/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n');
console.log(`Built ${6+news.length+productions.length} public pages; protected member route; Decap editor; ${news.length} news, ${team.length} team and ${productions.length} production entries.`);
