export const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const paragraphs = s => String(s||'').split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('');
export const imagePath = s => /^\/uploads\/[a-zA-Z0-9_./ -]+$/.test(s||'') && !s.includes('..') ? s : '';
export function picture(src,alt,cls=''){const p=imagePath(src);return p?`<img class="${esc(cls)}" src="${esc(p)}" alt="${esc(alt)}" loading="lazy" decoding="async">`:'';}
const links=[['/','Home'],['/news/','News'],['/team/','Our team'],['/whats-on/','What’s on'],['/productions/','Past productions'],['/join/','Join us'],['/members/','Members']];
export function layout(site,title,body,current='',privatePage=false){return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} · ${esc(site.name)}</title><meta name="description" content="${esc(site.name+' — '+site.description)}">${privatePage?'<meta name="robots" content="noindex,nofollow">':''}<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/productions.css"><script defer src="/site.js"></script></head><body class="${current==='/'?'home':'inner'}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/">${picture(site.logo,site.name+' '+site.description)}</a><nav aria-label="Main navigation">${links.map(([href,label])=>`<a href="${href}" ${current===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><div class="footer-brand">${picture(site.logo,site.name)}<p>${esc(site.description)}</p></div><div><a href="/privacy/">Privacy</a><a href="/admin/">Website editor</a></div></footer><dialog id="lightbox"><button type="button" class="lightbox-close">Close photograph</button><img alt=""><p></p></dialog></body></html>`;}
export function heading(kicker,title,intro=''){return `<section class="page-heading"><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1>${intro?`<p class="lead">${esc(intro)}</p>`:''}</section>`;}
export function membersPage(site,member){return layout(site,'Members',heading('Company members','Back in the rehearsal room',member.intro)+`<section class="reading"><h2>Rehearsals</h2>${paragraphs(member.rehearsals)}<h2>Company notices</h2>${paragraphs(member.notices)}<form action="/api/members/logout" method="post"><button class="button">Sign out</button></form></section>`,'/members/',true);}
export function loginPage(site,message=''){return layout(site,'Members',heading('Company members','Members area','Sign in with the company password to see rehearsal information and notices.')+`<section class="reading"><form id="member-login" class="form"><label for="password">Company password</label><input id="password" name="password" type="password" required maxlength="256" autocomplete="current-password"><div class="turnstile-slot" data-action="members"></div><button class="button" disabled>Sign in</button><p class="status" role="status">${esc(message||'Checking sign-in availability…')}</p></form></section>`,'/members/',true);}
