export const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const paragraphs = s => String(s||'').split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('');
export const imagePath = s => /^\/uploads\/[a-zA-Z0-9_./ -]+$/.test(s||'') && !s.includes('..') ? s : '';
export function picture(src,alt,cls=''){const p=imagePath(src);return p?`<img class="${esc(cls)}" src="${esc(p)}" alt="${esc(alt)}" loading="lazy" decoding="async">`:'';}
const links=[['/','Home'],['/news/','News'],['/team/','About us'],['/whats-on/','What’s on'],['/productions/','Past productions'],['/join/','Join us'],['/members/','Members']];
export function layout(site,title,body,current='',privatePage=false){const pageTitle=current==='/'?(site.homeSeoTitle||site.name+' | Musical Theatre in Plymouth'):title+' · '+site.name;const description=current==='/'?(site.homeSeoDescription||site.name+' — '+site.description):site.name+' — '+site.description;return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(pageTitle)}</title><meta name="description" content="${esc(description)}">${privatePage?'<meta name="robots" content="noindex,nofollow">':''}<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/productions.css"><script defer src="/site.js"></script></head><body class="${current==='/'?'home':'inner'}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/">${picture(site.logo,site.name+' '+site.description)}</a><nav aria-label="Main navigation">${links.map(([href,label])=>`<a href="${href}" ${current===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><div class="footer-brand">${picture(site.logo,site.name)}<p>${esc(site.description)}</p></div><div><div class="social-links" aria-label="Follow Top Hat and Tails"><a href="https://www.tiktok.com/@top.hat.and.tails3" target="_blank" rel="noopener noreferrer"><svg class="social-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-2.88 2.49 2.89 2.89 0 0 1-2.89-2.89 2.89 2.89 0 0 1 2.89-2.89c.3 0 .6.05.88.14V9.01a6.34 6.34 0 0 0-.88-.06 6.34 6.34 0 0 0-6.34 6.32 6.34 6.34 0 0 0 6.34 6.33 6.34 6.34 0 0 0 6.33-6.33V8.29a8.25 8.25 0 0 0 4.82 1.55V6.4c-.36 0-.71-.03-1.05-.1v.39Z"/></svg><span>TikTok</span><span aria-hidden="true">↗</span></a><a href="https://www.facebook.com/tophatandtailsmtc" target="_blank" rel="noopener noreferrer"><svg class="social-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="12" fill="#1877F2"/><path fill="#fff" d="M16.67 15.47l.53-3.47h-3.33V9.75c0-.95.47-1.88 1.96-1.88h1.51V4.92s-1.37-.23-2.68-.23c-2.73 0-4.51 1.66-4.51 4.67V12H7.12v3.47h3.03v8.39a12.2 12.2 0 0 0 3.72 0v-8.39h2.8Z"/></svg><span>Facebook</span><span aria-hidden="true">↗</span></a></div><div><a href="/privacy/">Privacy</a><a href="/admin/">Website editor</a></div></div></footer><dialog id="lightbox"><button type="button" class="lightbox-close">Close photograph</button><img alt=""><p></p></dialog></body></html>`;}
export function heading(kicker,title,intro=''){return `<section class="page-heading"><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1>${intro?`<p class="lead">${esc(intro)}</p>`:''}</section>`;}
export function membersPage(site,member){return layout(site,'Members',heading('Company members','Back in the rehearsal room',member.intro)+`<section class="reading"><h2>Rehearsals</h2>${paragraphs(member.rehearsals)}<h2>Company notices</h2>${paragraphs(member.notices)}<form action="/api/members/logout" method="post"><button class="button">Sign out</button></form></section>`,'/members/',true);}
export function loginPage(site,message=''){return layout(site,'Members',heading('Company members','Members area','Sign in with the company password to see rehearsal information and notices.')+`<section class="reading"><form id="member-login" class="form"><label for="password">Company password</label><input id="password" name="password" type="password" required maxlength="256" autocomplete="current-password"><div class="turnstile-slot" data-action="members"></div><button class="button" disabled>Sign in</button><p class="status" role="status">${esc(message||'Checking sign-in availability…')}</p></form></section>`,'/members/',true);}
